### ISSUE TITLE
Wrong player border color for the Gamemaster

### ISSUE THREAD

**Issue by lektu** [theripper93/camera-dock#1]
For some reason, it's not respecting the GM color when **Use player border colors** option is enabled. It briefly shows the GM's color, then it changes. This is in the Electron executable, but I was accessing the same session from Chrome and the GM color was wrong too.

![image](https://user-images.githubusercontent.com/833999/197397987-e7fa00af-9e5d-4adb-a5e8-ca185cc7b20b.png)

**Comment by theripper93** [comment]
Does this happen with all other modules off? Does this not happen with camera dock disabled? The module does not mess with colors so I find it very odd

**Comment by lektu** [comment]
I'll try without other modules, sorry I didn't think of it before.

I'm having another, bigger issue, but I'll try to reproduce it with no modules before reporting it.

**Comment by lektu** [comment]
![fallo2](https://user-images.githubusercontent.com/833999/197414885-a0df3f14-bf59-4098-a522-e90cc705904d.png)
![fallo1](https://user-images.githubusercontent.com/833999/197414886-931a5372-25b8-4ad6-a863-2333512923ba.png)

The same border, with just one module enabled (**Camera Dock**), and in two different game systems (_Cortex Prime_ and _Cypher System_).

**Comment by lektu** [comment]
It does happen with no modules other than Camera Dock, but it **does** happen without Camera Dock, so it's something in my side or some weird bug with core Foundry. Sorry for the noise.

**Comment by theripper93** [comment]
Yep, seems to be a core foundry bug
