### ISSUE TITLE
Moving cameras from bottom position

### ISSUE THREAD

**Issue by lektu** [theripper93/camera-dock#2]
I know the package is designed to move the cameras back to their default pre-V10 position. So I'm not asking for expanding Camera Dock to allow moving them to any other place.

On the contrary, I suggest making Camera Dock *not* to move the cameras anywhere even if the user happens to have the **Dock Position** option set to anything other than _Bottom_.

It's difficult to get a recipe for a specific result, but setting this option to different values and going back and forth between using Camera Dock and reverting to V10-style AV dock has caused, in my tests, quite an array of undesirable outcomes, from the whole interface disappearing (leaving only the cameras) to screwing the AV dock to the point it was unusable (out of place and/or lacking controls).

**Comment by theripper93** [comment]
In theory camera dock will set the settings correctly every time you load in if they are wrong, is that not the case?

**Comment by lektu** [comment]
This is:
- In the latest V10 release
- Using the Electron app on Windows.
- In a just created world.
- With no modules.
- Enable Audio & Video (the standard V10 dock)
- Move the dock to the left.
- Enable Camera Dock.

(This is the whole Foundry screen.)

![fallo](https://user-images.githubusercontent.com/833999/197535667-acfb8879-f5fe-40dc-8b5e-446f66ec8cc7.png)

**Comment by theripper93** [comment]
i cannot reproduce this, i can see your issue breeefly flashing on load, but then camera dock will change the camera settings accordingly, does the issue fixes itself on your end after an F5?

**Comment by lektu** [comment]
Yes, it fixes after an F5. But as I've said, when I tried going back and forth between V10 dock and Camera Dock, and from bottom to the other sides and back, eventually I got weird effects, more serious than the one above.

**Comment by theripper93** [comment]
I'm gonna need specific steps for that. Would removing the dock position option from the camera configuration solve most of the issues?

**Comment by lektu** [comment]
A recipe I can not give, because it doesn't always happen the same way, and I suspect having some modules will make things even more fragile.

But yes, I think removing the **Dock Position** option while the Camera Dock module is enabled will help, as long as the cameras do appear in the correct position regarding the option's value *before* enabling Camera Dock.

**Comment by theripper93** [comment]
The resetting will not work, as camera dock will change the settings so they can't be reverted easly. I'll remove the option and call it a day for this issues, because honestly if you wanna use it you are gonna keep it enabled, and not constantly toggle it on\off

**Comment by lektu** [comment]
I just tried with the new module, and the effect on the image above still happens.

For the record, this is not about constantly toggling anything, this is what happens (at least, on my Electron instance) if you, for whatever reason, have the standard V10 dock on the left *before* you enable Camera Dock. It can be fixed, but not just F5, I had to do a full reload (Ctrl-F5).

So perhaps something to note in the README.

**Comment by lozanoje** [comment]
A reproducible example, move dock to the left and then activate camera-dock:

https://youtu.be/oS2TcLdTHv0

The latest flashes are F5 and CTRL-F5. I am using latest Foundry+Camera dock in a nodejs installation under Windows 11 + Edge Browser.

**Comment by theripper93** [comment]
It seems i can repro in a new world, there is definatelly some core foundry bug here

**Comment by theripper93** [comment]
i've reported the issue here, you can follow it if you want https://github.com/foundryvtt/foundryvtt/issues/8423

**Comment by theripper93** [comment]
For now i've made a crude fix for this, as in i've set a 5 second timeout before changing the setting, while it might look ugly at least it will not break the interface

**Comment by lozanoje** [comment]
Perfect, thank you!
