### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by lektu** [theripper93/camera-dock#3]
Just a suggestion, but adding some keybindings would be really helpful. (I think too few modules use keybindings.)

Having one to cycle the size of all **Camera Dock** windows would be really great. Also for muting/disabling audio and/or video, etc.

**Comment by theripper93** [comment]
Feature requests on my discord, i forgot to get the disclamer in the repo :p

Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
