### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by dmpunks** [theripper93/camera-dock#5]
Foundry VTT V10, Build 291
Dnd53 - Fifth Edition System 2.1.4
Active Modules: 2
Other settings: Core > Audio/Video Configuration > A/V Configuration Mode = Audio/Video Enabled

I noticed I'm getting the following console errors when Camera Dock is enabled as a module. There are 2 errors if only Camera Dock is enable; 3 errors if libwrapper is enabled also.

![image](https://user-images.githubusercontent.com/1963509/216968095-c61bb4c2-11a5-4cb5-97ed-5f6b9611b6e2.png)
![image](https://user-images.githubusercontent.com/1963509/216968151-acd6f9b4-5b12-4f56-8282-85479b04e009.png)

[It doesn't seem to block anything, as the audio and video still works; I just stumbled into this while troubleshooting why my server intermittently crashes all clients with the Oh Snap! error in Google Chrome during game sessions, so I wanted to cross this out. BTW thanks for this great module, theripper!]

**Comment by theripper93** [comment]
I've been trying to isolate which of my modules caused this error, thanks so much for isolating lol. I don't belive this error does anything in practice, but i'll try to figure out why it happens

**Comment by dmpunks** [comment]
Awesome, thanks!

**Comment by theripper93** [comment]
So, basically i can't do much for these errors, it's core complaining with camera dock dismantling the cameras UI completely. You can ignore them as i don't have a fix for them
