### ISSUE TITLE
Black bar at the top of screen

### ISSUE THREAD

**Issue by Krigsmaskine** [theripper93/camera-dock#7]
**I have disabled all other modules: **True
**Module(s) **Camera Dock
**Conflicting Module(s) **
**Foundry and System version **Foundry v10.291, DnD5e 2.1.5
**OS, Hosting, Browser (if applicable) **Local host and local app
**Short description of bug **There is an element in the html called 'camera-view-width-control' introduced by the module that leaves a black bar across the top of the window with seemingly no function.
**Simple steps to reproduce the bug **

Create fresh new DnD5e world, enable Camera Dock and behold a small black bar at the top.

**Screenshots and/or Console Errors**
This is with Camera Dock enabled on a fresh world.
![image](https://user-images.githubusercontent.com/39592771/233345356-0638bd20-e92f-46e8-a90b-398b7ec1bd6b.png)

With Camera Dock disabled.
![image](https://user-images.githubusercontent.com/39592771/233345990-c58a7d77-f70b-4917-9ed4-0478abf61bab.png)

I personally fixed it with just some custom css and `display: none;`, but I figured it was worth mentioning 'cause nailing down it was camera related took a while.

**Comment by theripper93** [comment]
Thanks for spotting it, fixed (it was actually bothering me in my games lol)
