### ISSUE TITLE
[Suggestion] Hide symbols

### ISSUE THREAD

**Issue by zimm44** [theripper93/camera-dock#8]
Auto hide the symbols on top of the camera area if it's not activated on the server. Example: Server is set to "Video Only", then hide the muted audio buttom since it doesn't play any role in this server.

![image](https://github.com/theripper93/camera-dock/assets/67938397/b1075666-59e3-451a-984f-9ae39ddc5c66)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
