### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by Oxy949** [theripper93/camera-dock#9]
Hi. Tried this module in Foundry 12.327. Everything seems to work fine, but there is a problem. Gamemaster doesn't see other players (no portraits) when they are connected. We tested without the module and everything works fine.

![image](https://github.com/theripper93/camera-dock/assets/7158560/c686073a-6004-4de3-8981-6b7bb09d1409)

Many duplicates of the error appear in the browser console:
```
Error: An error occurred while rendering CameraViews 6. Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13Caused by: DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at AVMaster.onRender (***/scripts/foundry.js:92224:82)
    at CameraViews._render (***/scripts/foundry.js:83529:17)
```

**Comment by theripper93** [comment]
The issue is fixed, note that you will still see that error, that is unavoidable due to the hacky nature of this module
